### ISSUE TITLE
Beta feedback

### ISSUE THREAD

**Issue by kaelig** [kaelig/readhn#5]
Leave your feedback here!

Note: read.hn was initially built for my very own (niche) use case and so I could learn a bit more about JavaScript, so be gentle :)

**Comment by kaelig** [comment]
@csswizardry @yodasw16 @Keirua thank you for your interest, it means a lot! Any feedback is welcome here.

Tip: add to homescreen. I've been using it for the past two weeks and I wonder what other people would do with it.

**Comment by b0o** [comment]
@kaelig This is very cool, great job! 

After just a few minutes of usage, my only suggestion so far is to allow users to customize their font settings so they can match their Instapaper settings.

Also, I'm not sure how useful the three links (Search, Refresh, HN) at the top of the page are, perhaps they'd be better at the bottom?

**Comment by kaelig** [comment]
Thank you for the feedback! I’ll definitely try to think of a way to allow theme customization without bloating the experience.

**Comment by kaelig** [comment]
Closing this as it is stale and I'm cleaning up my issues.
